
version: '3'

services:

  cfgsvr2:
    container_name: cfgsvr2
    image: mongo
    command: mongod --configsvr --auth --replSet cfgrs --port 27017 --dbpath /data/db --oplogSize 16 --keyFile /mongodb.key
    ports:
      - 40002:27017
    volumes:
      - cfgsvr2:/data/db
      - ./mongodb.key:/mongodb.key

volumes:
  cfgsvr2: {}
