
version: '3'

services:

  cfgsvr1:
    container_name: cfgsvr1
    image: mongo
    command: mongod --auth --configsvr --replSet cfgrs --port 27017 --dbpath /data/db --oplogSize 16 --keyFile /mongodb.key
    ports:
      - 40001:27017
    volumes:
      - cfgsvr1:/data/db
      - ./mongodb.key:/mongodb.key

volumes:
  cfgsvr1: {}
