
version: '3'

services:

  mongos:
    container_name: mongos
    image: mongo
    command: mongos --configdb cfgrs/192.168.1.193:40001,192.168.1.194:40002,192.168.1.195:40003 --bind_ip 0.0.0.0 --port 27017 --keyFile /mongodb.key
    volumes:
      - ./mongodb.key:/mongodb.key
    ports:
      - 60000:27017
