
version: '3'

services:

  shard2svr1:
    container_name: shard2svr1
    image: mongo
    command: mongod --auth --shardsvr --replSet shard2rs --port 27017 --dbpath /data/db --oplogSize 16 --keyFile /mongodb.key
    ports:
      - 50004:27017
    volumes:
      - shard2svr1:/data/db
      - ./mongodb.key:/mongodb.key

volumes:
  shard2svr1: {}

